/**
 * JaskierAPI
 * This is the API for [Jaskier](https://github.com/4lch4/Jaskier). Some of the endpoints are locked to admin tokens for the production version but anyone is more than welcome to stand up their own version for whatever you want. Feel free to reach out to me online via any of the methods listed on [my personal website](https://alcha.org). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@4lch4.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Order { 
    id?: number;
    petId?: number;
    quantity?: number;
    shipDate?: Date;
    /**
     * Order Status
     */
    status?: Order.StatusEnum;
    complete?: boolean;
}
export namespace Order {
    export type StatusEnum = 'placed' | 'approved' | 'delivered';
    export const StatusEnum = {
        Placed: 'placed' as StatusEnum,
        Approved: 'approved' as StatusEnum,
        Delivered: 'delivered' as StatusEnum
    };
}